-- CheatMeals — jokes seed ("while you wait" one-liners).
-- Generated from _reference/jokes-source.json by _reference/gen-jokes.mjs
-- (run that to regenerate after editing the source). Do not edit by hand.
-- Idempotent: clears the table then re-inserts the full set, so re-running
-- (or `supabase db reset`) always yields exactly the source rows.
-- sort_order is 0-based per language, following source order.
begin;

delete from public.jokes;

insert into public.jokes (lang, category, text, sort_order) values
  ('en', 'burger', 'The Red Hulk is double aloo patty energy. It does not smash buildings, just your small hunger plans.', 0),
  ('en', 'food', 'Our patties are house-made because frozen patties do not understand commitment.', 1),
  ('en', 'wait', 'Choosing from this menu counts as cardio for your brain.', 2),
  ('en', 'burger', 'Aloo 420 is not a scam. It just steals your attention and refuses to apologize.', 3),
  ('en', 'dad', 'Why did the burger sit down? It was tired of being on a roll.', 4),
  ('en', 'food', 'The secret sauce is secret because even the fries keep asking too many questions.', 5),
  ('en', 'burger', 'Aloo Anarkali has main character energy. One bite and your plain lunch starts feeling underdressed.', 6),
  ('en', 'desi', 'This is the kind of food that makes your inner uncle say, beta, order one more for the table.', 7),
  ('en', 'wait', 'Your burger is being made fresh. Your patience is also being lightly toasted.', 8),
  ('en', 'food', 'Every burger comes with a side because even legends need backup.', 9),
  ('en', 'burger', 'Amdavadi Chaska is not a flavour. It is a polite addiction wearing chutney.', 10),
  ('en', 'dad', 'I told my fries a joke. They said it was seasoned well.', 11),
  ('en', 'food', 'Loaded Fries are what happens when regular fries finally get promoted.', 12),
  ('en', 'wait', 'Waiting is hard. But so is explaining why you ordered only one burger.', 13),
  ('en', 'burger', 'Red Devil sounds spicy, but the real danger is thinking you will share it.', 14),
  ('en', 'desi', 'This food is basically comfort, crunch, and one tiny voice saying, pack extra for later.', 15),
  ('en', 'food', 'Seasoned Fries: because plain potatoes had dreams too.', 16),
  ('en', 'burger', 'Paneer burgers walk in soft, leave with full desi street confidence.', 17),
  ('en', 'dad', 'What did the patty say to the bun? I am falling for you, layer by layer.', 18),
  ('en', 'wait', 'By the time you pick a sauce, your hunger has already written a complaint letter.', 19),
  ('en', 'burger', 'Schezwan Aloo Tikki has a simple personality: hello, crunch, plot twist.', 20),
  ('en', 'desi', 'Jugaad is turning one bite into a full dinner plan.', 21),
  ('en', 'food', 'Frankies are rolls with confidence. They know exactly how much chaos they can hold.', 22),
  ('en', 'wait', 'This is your official reminder: staring at the counter does not cook the burger faster.', 23),
  ('en', 'burger', 'Home of Indian Burgers means the bun showed up, but the masala took over the meeting.', 24),
  ('en', 'dad', 'Why did the tomato blush? Because it saw the salad dressing.', 25),
  ('en', 'food', 'Fries are just potatoes that finally found their purpose.', 26),
  ('en', 'wait', 'The food is not late. Your hunger is just being dramatic.', 27),
  ('en', 'dad', 'I asked the bun for advice. It said, stay grounded, but rise when needed.', 28),
  ('en', 'desi', 'Desi homes do not have snacks. They have emergency happiness stored in steel boxes.', 29),
  ('en', 'food', 'Sauce is proof that food can have a personality.', 30),
  ('en', 'wait', 'Waiting for food builds character. Mostly hungry character.', 31),
  ('en', 'dad', 'Why did the plate apply for a job? It wanted to serve.', 32),
  ('en', 'food', 'Crunch is just food applause.', 33),
  ('en', 'desi', 'A true desi snack is never measured. It is judged by vibes and second helpings.', 34),
  ('en', 'wait', 'Your order is coming. Your stomach has already started rehearsing its thank-you speech.', 35),
  ('en', 'dad', 'I tried to make a sandwich laugh, but it was too pressed.', 36),
  ('en', 'food', 'A good meal does not ask questions. It answers them.', 37),
  ('en', 'desi', 'There are two desi settings: just ate and still looking for something small.', 38),
  ('en', 'dad', 'Why did the spoon win the argument? It had a stirring point.', 39),
  ('en', 'wait', 'This is the quiet part where everyone pretends they are not checking the kitchen.', 40),
  ('en', 'food', 'The best smell is food arriving at someone else''s table, giving you hope.', 41),
  ('en', 'dad', 'I told my lunch a secret. Now it is a wrap.', 42),
  ('en', 'desi', 'Tea time is not a time. It is a lifestyle with biscuits.', 43),
  ('en', 'wait', 'Hunger makes every minute feel like it has extra minutes inside.', 44),
  ('en', 'food', 'A snack before food is just a trailer for the main movie.', 45),
  ('en', 'dad', 'Why did the fork break up with the spoon? Too much stirring drama.', 46),
  ('en', 'desi', 'In a desi house, leftovers are not leftovers. They are tomorrow''s comeback story.', 47),
  ('en', 'wait', 'You are not impatient. You are just emotionally invested in lunch.', 48),
  ('en', 'food', 'Good food does not need a speech. It just needs one silent first bite.', 49),
  ('en', 'dad', 'Why did the pickle stay calm? It was already in a jar of peace.', 50),
  ('en', 'desi', 'Someone says just one bite, and suddenly half the plate has disappeared politely.', 51),
  ('en', 'wait', 'Your stomach called. It said no pressure, but also hurry.', 52),
  ('hi', 'burger', 'रेड हल्क को देखकर भूख ने कहा, मैं तो बस स्नैक लेने आया था।', 0),
  ('hi', 'food', 'हमारी पैटी घर की बनी है। फ्रीज़र वाली पैटी से इतना प्यार नहीं हो पाता।', 1),
  ('hi', 'wait', 'मेन्यू देखकर फैसला लेना आसान नहीं है। भूख अंदर से बोलती है, सब टिक कर दे।', 2),
  ('hi', 'burger', 'आलू 420 चोरी नहीं करता। बस पहला बाइट लेते ही दिल अपने नाम कर लेता है।', 3),
  ('hi', 'dad', 'बर्गर ने फ्राइज से कहा, तू साथ हो तो प्लेट भी परिवार लगती है।', 4),
  ('hi', 'food', 'सीक्रेट सॉस का राज वही जानता है जो चुपचाप एक्स्ट्रा मांगता है।', 5),
  ('hi', 'burger', 'आलू अनारकली ऐसी है कि भूख भी कहे, वाह, एंट्री तो फिल्मी है।', 6),
  ('hi', 'desi', 'यहाँ का बर्गर खाकर वही फील आता है: पेट फुल, दिल खुश, और मन में पैकिंग का प्लान।', 7),
  ('hi', 'wait', 'आपका बर्गर बन रहा है। तब तक अपनी भूख को समझाइए कि ड्रामा कम करे।', 8),
  ('hi', 'food', 'हर बर्गर के साथ साइड आती है, क्योंकि अकेला हीरो भी कभी-कभी टीम लेकर चलता है।', 9),
  ('hi', 'burger', 'अमदावादी चस्का नाम नहीं, मूड है। एक बार लग गया तो फिर बस वही चाहिए।', 10),
  ('hi', 'dad', 'फ्राइज इतने करारे थे कि चुप्पी भी क्रंच करने लगी।', 11),
  ('hi', 'food', 'लोडेड फ्राइज देखकर सादी फ्राइज ने कहा, आज तो तू पूरा फंक्शन बन गई।', 12),
  ('hi', 'wait', 'भूख का टाइम पास: मेन्यू पढ़ना, फिर वही चीज़ तीन बार दोबारा पढ़ना।', 13),
  ('hi', 'burger', 'रेड डेविल तीखा है, पर असली आग तब लगती है जब दोस्त बोले, थोड़ा शेयर कर।', 14),
  ('hi', 'desi', 'देसी कम्फर्ट फूड वही है जो पहले पेट भरता है, फिर आत्मा को हाई-फाइव देता है।', 15),
  ('hi', 'food', 'सीज़न्ड फ्राइज: आलू का वह रूप, जिसे खुद आलू भी देखकर बोले, बढ़िया लग रहा हूँ।', 16),
  ('hi', 'burger', 'पनीर बर्गर नरम दिल वाला है, लेकिन स्वाद में पूरा कॉन्फिडेंट।', 17),
  ('hi', 'dad', 'पैटी ने बन से कहा, तू ऊपर रह, मैं मामला संभालता हूँ।', 18),
  ('hi', 'wait', 'ऑर्डर के बाद सबसे लंबा मिनट वही होता है, जिसमें खुशबू पास से गुजरती है।', 19),
  ('hi', 'burger', 'शेज़वान आलू टिक्की पहले क्रंच देती है, फिर बोलती है, अब मसाला संभाल।', 20),
  ('hi', 'desi', 'जुगाड़ का असली मतलब: एक बर्गर, दो साइड, और दिमाग में तीसरे ऑर्डर की जगह।', 21),
  ('hi', 'food', 'फ्रैंकी रोल नहीं, चलता-फिरता भरोसा है। पकड़ो और जिंदगी थोड़ी आसान लगती है।', 22),
  ('hi', 'wait', 'काउंटर को घूरने से बर्गर जल्दी नहीं बनता, पर मन को थोड़ी उम्मीद मिलती है।', 23),
  ('hi', 'burger', 'होम ऑफ इंडियन बर्गर्स में बन बाहर से आया, पर अंदर पूरा देसी जलवा बैठा है।', 24),
  ('hi', 'dad', 'टमाटर लाल क्यों हुआ? क्योंकि सलाद की ड्रेसिंग देख ली।', 25),
  ('hi', 'food', 'फ्राइज वही आलू हैं जिन्हें जिंदगी में सही दिशा मिल गई।', 26),
  ('hi', 'wait', 'खाना लेट नहीं है। आपकी भूख बस थोड़ा ओवरएक्टिंग कर रही है।', 27),
  ('hi', 'dad', 'बन ने कहा, ऊपर रहना आसान नहीं, हर बात का टॉपिंग बनना पड़ता है।', 28),
  ('hi', 'desi', 'देसी घर में स्नैक्स नहीं होते, स्टील के डब्बों में खुशियाँ रखी होती हैं।', 29),
  ('hi', 'food', 'सॉस सबूत है कि खाने की भी पर्सनैलिटी हो सकती है।', 30),
  ('hi', 'wait', 'खाने का इंतज़ार इंसान को मजबूत बनाता है। खासकर पेट की आवाज़ को।', 31),
  ('hi', 'dad', 'प्लेट ने नौकरी क्यों ढूँढी? उसे सर्व करना पसंद था।', 32),
  ('hi', 'food', 'क्रंच खाने की तालियाँ हैं।', 33),
  ('hi', 'desi', 'सच्चा देसी स्नैक नापा नहीं जाता, बस मन से डाला जाता है।', 34),
  ('hi', 'wait', 'आपका ऑर्डर आ रहा है। पेट ने धन्यवाद भाषण अभी से तैयार कर लिया है।', 35),
  ('hi', 'dad', 'सैंडविच को हँसाने की कोशिश की, पर वह बहुत प्रेस्ड था।', 36),
  ('hi', 'food', 'अच्छा खाना सवाल नहीं पूछता, सीधे जवाब देता है।', 37),
  ('hi', 'desi', 'देसी मोड दो ही होते हैं: अभी खाया है और फिर भी कुछ हल्का चाहिए।', 38),
  ('hi', 'dad', 'चम्मच बहस क्यों जीत गया? उसके पास घुमाकर बात करने का हुनर था।', 39),
  ('hi', 'wait', 'यह वही समय है जब सब चुपचाप किचन की तरफ उम्मीद से देखते हैं।', 40),
  ('hi', 'food', 'सबसे अच्छी खुशबू वही है जो किसी और की प्लेट से आती है और आपको भरोसा देती है।', 41),
  ('hi', 'dad', 'लंच को राज़ बताया, अब वह रैप बन गया।', 42),
  ('hi', 'desi', 'चाय का टाइम घड़ी से नहीं, दिल से तय होता है।', 43),
  ('hi', 'wait', 'भूख में हर मिनट के अंदर दो एक्स्ट्रा मिनट छुपे होते हैं।', 44),
  ('hi', 'food', 'खाने से पहले वाला स्नैक असली फिल्म का ट्रेलर है।', 45),
  ('hi', 'dad', 'फोर्क और स्पून की दोस्ती क्यों टूटी? बहुत ज्यादा स्टिरिंग ड्रामा हो गया।', 46),
  ('hi', 'desi', 'बचा हुआ खाना बचा हुआ नहीं होता, वह कल की कमबैक स्टोरी होती है।', 47),
  ('hi', 'wait', 'आप बेसब्र नहीं हैं। आप बस लंच में भावनात्मक रूप से निवेश कर चुके हैं।', 48),
  ('hi', 'food', 'अच्छे खाने को भाषण नहीं चाहिए, बस पहला शांत बाइट चाहिए।', 49),
  ('hi', 'dad', 'अचार इतना शांत क्यों था? क्योंकि वह पहले से ही जार में सेटल था।', 50),
  ('hi', 'desi', 'कोई कहता है बस एक बाइट, और प्लेट आधी बहुत इज़्ज़त से गायब हो जाती है।', 51),
  ('hi', 'wait', 'पेट का मैसेज आया है: कोई प्रेशर नहीं, बस जल्दी कर दो।', 52);

commit;
